# Generated by Django 5.1.1 on 2024-10-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_alter_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.TextField(null=True),
        ),
    ]
