# Generated by Django 5.1.1 on 2024-10-18 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_alter_book_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, max_length=50)),
                ('img', models.ImageField(upload_to='image')),
                ('about', models.CharField(blank=None, max_length=200)),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.instrument')),
            ],
        ),
    ]
