# Generated by Django 5.1.1 on 2024-10-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, upload_to='image')),
                ('heading', models.CharField(blank=None, max_length=100)),
                ('main', models.TextField(blank=None, max_length=200)),
            ],
        ),
    ]
