# Generated by Django 5.1.2 on 2024-10-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0010_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.CharField(blank=True, max_length=5)),
                ('image', models.ImageField(blank=None, upload_to='image')),
            ],
        ),
    ]
