# Generated by Django 5.1.2 on 2024-11-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0011_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testmonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=None, upload_to='image')),
                ('name', models.CharField(blank=None, max_length=100)),
                ('profession', models.CharField(blank=None, max_length=80)),
                ('message', models.TextField(blank=None, max_length=150)),
            ],
        ),
    ]
