# Generated by Django 5.1.2 on 2024-11-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0013_alter_testmonial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
