# Generated by Django 5.1.2 on 2024-11-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0015_seat_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
